### ISSUE TITLE
VocabularyLoadRunner Failing in release 1.0.18

### ISSUE THREAD

**Issue by markarnott** [siteadmin/reference-ccda-validator#14]
I am upgrading from the 1.0.10 release and I see an error message in the log file. 
It appears that the VocabularyLoadRunner wants the VSAC value set files to be in xslx (OOXML) format instead of the xsl format that was used in earlier versions.

Here is the content from the log file.

15:14:46,888 INFO  [VocabularyLoadRunner:99] Loading value sets at: E:\ValidationService\ReferenceCcdaService\Vocabulary\valueset_repository...
15:14:46,888 INFO  [VocabularyLoadRunner:44] Loading files in : VSAC...
15:14:46,888 INFO  [VsacLoader:34] Loading Value Set File: Ability.xls
15:14:46,903 ERROR [VocabularyLoadRunner:107] Failed to load configured vocabulary directory.
org.apache.poi.openxml4j.exceptions.OLE2NotOfficeXmlFileException: The supplied data appears to be in the OLE2 Format. You are calling the part of POI that deals with OOXML (Office Open XML) Documents. You need to call a different part of POI to process this data (eg HSSF instead of XSSF)
	at org.apache.poi.openxml4j.opc.internal.ZipHelper.verifyZipHeader(ZipHelper.java:172)
	at org.apache.poi.openxml4j.opc.internal.ZipHelper.openZipFile(ZipHelper.java:257)
	at org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:137)
	at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:305)
	at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:201)
	at com.monitorjbl.xlsx.impl.StreamingWorkbookReader.init(StreamingWorkbookReader.java:97)
	at com.monitorjbl.xlsx.impl.StreamingWorkbookReader.init(StreamingWorkbookReader.java:77)
	at com.monitorjbl.xlsx.StreamingReader$Builder.open(StreamingReader.java:228)
	at org.sitenv.vocabularies.loader.valueset.VsacLoader.load(VsacLoader.java:37)
	at org.sitenv.vocabularies.loader.VocabularyLoadRunner.load(VocabularyLoadRunner.java:45)
	at org.sitenv.vocabularies.loader.VocabularyLoadRunner.loadDirectory(VocabularyLoadRunner.java:32)
	at org.sitenv.vocabularies.loader.VocabularyLoadRunner.afterPropertiesSet(VocabularyLoadRunner.java:100)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:446)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:328)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4810)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:586)
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1777)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Please advise regarding how we get data in the correct format.  The documentation in the Code-Validator-Api repository still indicates that these files should be in xls format.

**Comment by Plow74** [comment]
Very sorry, Mark. I completely missed updating the documentation on the code validator API. The loader does expect the files to be in xslx. This is to facilitate loading the larger VSAC valuesets. I wish there was a super-easy way to do this, and perhaps there is and I just don't know it, but I want to each file and just did a save as to the new file extension. Please let me know if you have any questions or concerns.

**Comment by markarnott** [comment]
I have created a pull request on code-validator-api.  

As far as I am concerned, we can close this issue once we get those Value Sets in XSLX format.

I did go back out to NLM's VSAC site and all their value sets are now downloadable in an xslx format.
