### ISSUE TITLE
Null return value from advice does not match primitive return type for: public abstract boolean 

### ISSUE THREAD

**Issue by usmanq8** [siteadmin/reference-ccda-validator#30]
I am blank as to why i got his error:
i am using "170.315_b1_toc_amb_ccd_r21_sample1_v12.xml" provided for certification.

03-08-2018 17:07:38 [ERROR] ReferenceCCDAValidationService.processValidateCCDAException:104 - The service has encountered the following error: org.springframework.aop.AopInvocationException: Null return value from advice does not match primitive return type for: public abstract boolean org.sitenv.vocabularies.validation.repositories.CodeRepository.codeIsActive(java.lang.String,java.util.Set)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:221)
	at com.sun.proxy.$Proxy57.codeIsActive(Unknown Source)
	at org.sitenv.vocabularies.validation.validators.nodetypes.CodeSystemCodeValidator.validateNode(CodeSystemCodeValidator.java:74)
	at org.sitenv.vocabularies.validation.services.VocabularyValidationService.validate(VocabularyValidationService.java:113)
	at org.sitenv.vocabularies.validation.services.VocabularyValidationService.validate(VocabularyValidationService.java:75)
	at org.sitenv.referenceccda.validators.vocabulary.VocabularyCCDAValidator.doValidation(VocabularyCCDAValidator.java:59)
	at org.sitenv.referenceccda.validators.vocabulary.VocabularyCCDAValidator.validateFileImplementation(VocabularyCCDAValidator.java:49)
	at org.sitenv.referenceccda.validators.vocabulary.VocabularyCCDAValidator.validateFile(VocabularyCCDAValidator.java:39)
	at org.sitenv.referenceccda.services.ReferenceCCDAValidationService.doVocabularyValidation(ReferenceCCDAValidationService.java:191)
	at org.sitenv.referenceccda.services.ReferenceCCDAValidationService.runValidators(ReferenceCCDAValidationService.java:131)
	at org.sitenv.referenceccda.services.ReferenceCCDAValidationService.validateCCDAImplementation(ReferenceCCDAValidationService.java:72)
	at org.sitenv.referenceccda.services.ReferenceCCDAValidationService.validateCCDA(ReferenceCCDAValidationService.java:58)

**Comment by usmanq8** [comment]
![resulterror](https://user-images.githubusercontent.com/41000007/43648300-6e9a0e96-9753-11e8-85cb-a63bfef09591.PNG)
this is what i get on local Tomcat after running the file

**Comment by drbgfc** [comment]
Are you using this 1.0.33 (latest) version of the WAR?
https://github.com/siteadmin/reference-ccda-validator/releases/tag/1.0.33

**Comment by usmanq8** [comment]
Thanks. Issue got resolved after taking latest source code.

**Comment by jasoncmedent** [comment]
I'm actually still having this error, and I'm using the 1.0.33 WAR. It also happens with the test tool validator as well. I've attached the (de-identified) referral note I'm testing with. 


Thank You 
Jason Countryman 

This message and any attachments may contain information that is protected by law as privileged and confidential, and is transmitted for the sole use of the intended recipient(s). If you are not the intended recipient, you are hereby notified that any use, dissemination, copying or retention of this e-mail or the information contained herein is strictly prohibited. If you received this e-mail in error, please immediately notify the sender by e-mail, and permanently delete this e-mail.

**Comment by drbgfc** [comment]
I will look into this - thanks!

**Comment by drbgfc** [comment]
Update: I have reproduced this on my local machine. It is related to LOINC, but not related to the version, so unrelated to the fix for this month which allows for the latest LOINC version in addition to older ones. I have never seen the issue happen in any other file but the one you sent. I will keep isolating the issue and resolve. Thanks for the patience.

**Comment by jasoncmedent** [comment]
Thank you, Dan, for your time on this. I appreciate it. 


Thank You 
Jason Countryman 

This message and any attachments may contain information that is protected by law as privileged and confidential, and is transmitted for the sole use of the intended recipient(s). If you are not the intended recipient, you are hereby notified that any use, dissemination, copying or retention of this e-mail or the information contained herein is strictly prohibited. If you received this e-mail in error, please immediately notify the sender by e-mail, and permanently delete this e-mail.

**Comment by drbgfc** [comment]
@jasoncmedent - do you ever build the ref val yourself? If so, this appears to resolve the issue:
Changing the query on line 37 in /codevalidator-api/src/main/java/org/sitenv/vocabularies/validation/repositories/CodeRepository.java to

``@Query("SELECT c.active FROM Code c WHERE c.code = :code and c.codeSystem in (:codesystems)")``

Plenty of testing will need to be done to verify it doesn't cause any other issues or miss any results. For the file you sent, it takes a long time, but typical files seem to perform about the same.

**Comment by jasoncmedent** [comment]
I've actually never been able to get a working ref val build on my own, even without modifications to the code. 

Thank You 
Jason Countryman 

This message and any attachments may contain information that is protected by law as privileged and confidential, and is transmitted for the sole use of the intended recipient(s). If you are not the intended recipient, you are hereby notified that any use, dissemination, copying or retention of this e-mail or the information contained herein is strictly prohibited. If you received this e-mail in error, please immediately notify the sender by e-mail, and permanently delete this e-mail.

**Comment by drbgfc** [comment]
Sorry about that. Here are the results, maybe that will help somewhat for now...
[jasonC-results.txt](https://github.com/siteadmin/reference-ccda-validator/files/2279216/jasonC-results.txt)

**Comment by drbgfc** [comment]
Hi Jason,
This issue has been resolved in https://github.com/siteadmin/reference-ccda-validator/releases/tag/1.0.34 /SITE 3.1.18 which was released yesterday. Closing the issue.
It does however take a VERY LONG time to validate since it is a large file. By that I mean in the range of 15-20 minutes. Apologies for that, but, just so you know it is not stuck in a loop but actually chugging along. I'm guessing an IG only test would be dramitically faster than this (IG + Vocab).

Thanks,
Dan

**Comment by jasoncmedent** [comment]
Thanks, Dan. 

Yeah, this file is definitely a torture test. Thanks for looking into this. 

Thank You 
Jason Countryman 

This message and any attachments may contain information that is protected by law as privileged and confidential, and is transmitted for the sole use of the intended recipient(s). If you are not the intended recipient, you are hereby notified that any use, dissemination, copying or retention of this e-mail or the information contained herein is strictly prohibited. If you received this e-mail in error, please immediately notify the sender by e-mail, and permanently delete this e-mail.

**Comment by drbgfc** [comment]
Hah indeed - np
