### ISSUE TITLE
ConcurrentModificationException when called validator in Multi threaded Env.

### ISSUE THREAD

**Issue by usmanq8** [siteadmin/reference-ccda-validator#31]
We have multi threaded processes and need to validate files in parallel.
I am using **170.315_b1_ToC_Amb** profiles to test them.
I have written my own method to call API validate method i.e. as below:

```
public ValidationResultsDto validateCCDA (File file) throws FileNotFoundException, IOException{
		
		ReferenceCCDAValidationService refValidator = (ReferenceCCDAValidationService) validatorContext.getBean(ReferenceCCDAValidationService.class);
		ValidationResultsDto result = null;
		MultipartFile mockSample = null;
		try(FileInputStream is = new FileInputStream(file)) {
			mockSample = new MockMultipartFile(file.getName(), file.getName(),"text/xml", is);
			result = refValidator.validateCCDA(CCDATypes.CCDAR21_OR_CCDAR11, "sample", mockSample);
			is.close();
		}
		return result;
	}
```
Which raises `ConcurrentModificationException`

```

07-08-2018 12:20:11 [INFO] ReferenceCCDAValidationService.doMDHTValidation:180 - Attempting MDHT validation...
07-08-2018 12:20:11 [WARN] ReferenceCCDAValidator.mapMdhtValidationObjective:294 - An invalid validationObjective was POSTed
07-08-2018 12:20:11 [INFO] ReferenceCCDAValidator.validateDocumentByTypeUsingMDHTApi:140 - Mapped mdhtValidationObjective: NonSpecificCCDAR2
07-08-2018 12:20:11 [WARN] ReferenceCCDAValidator.mapMdhtValidationObjective:294 - An invalid validationObjective was POSTed
07-08-2018 12:20:11 [INFO] ReferenceCCDAValidator.validateDocumentByTypeUsingMDHTApi:140 - Mapped mdhtValidationObjective: NonSpecificCCDAR2
07-08-2018 12:20:11 [WARN] ReferenceCCDAValidator.mapMdhtValidationObjective:294 - An invalid validationObjective was POSTed
07-08-2018 12:20:11 [INFO] ReferenceCCDAValidator.validateDocumentByTypeUsingMDHTApi:140 - Mapped mdhtValidationObjective: NonSpecificCCDAR2
07-08-2018 12:20:11 [WARN] ReferenceCCDAValidator.mapMdhtValidationObjective:294 - An invalid validationObjective was POSTed
07-08-2018 12:20:11 [INFO] ReferenceCCDAValidator.validateDocumentByTypeUsingMDHTApi:140 - Mapped mdhtValidationObjective: NonSpecificCCDAR2
07-08-2018 12:20:12 [INFO] ReferenceCCDAValidator.validateDocumentByTypeUsingMDHTApi:151 - Loading mdhtValidationObjective: NonSpecificCCDAR2 mapped from valdationObjective: C-CDA_IG_Plus_Vocab
07-08-2018 12:20:12 [INFO] ReferenceCCDAValidator.validateDocumentByTypeUsingMDHTApi:151 - Loading mdhtValidationObjective: NonSpecificCCDAR2 mapped from valdationObjective: C-CDA_IG_Plus_Vocab
07-08-2018 12:20:12 [INFO] ReferenceCCDAValidator.validateDocumentByTypeUsingMDHTApi:151 - Loading mdhtValidationObjective: NonSpecificCCDAR2 mapped from valdationObjective: C-CDA_IG_Plus_Vocab
07-08-2018 12:20:12 [ERROR] ReferenceCCDAValidationService.processValidateCCDAException:100 - The service has encountered the following error: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:922)
	at java.util.HashMap$KeyIterator.next(HashMap.java:956)
	at org.hl7.security.ds4p.contentprofile.impl.CONTENTPROFILEPackageImpl.unload(CONTENTPROFILEPackageImpl.java:425)	at org.sitenv.referenceccda.validators.schema.ReferenceCCDAValidator.validateDocumentByTypeUsingMDHTApi(ReferenceCCDAValidator.java:149)	at org.sitenv.referenceccda.validators.schema.ReferenceCCDAValidator.validateFile(ReferenceCCDAValidator.java:97)	at org.sitenv.referenceccda.services.ReferenceCCDAValidationService.doMDHTValidation(ReferenceCCDAValidationService.java:181)	at org.sitenv.referenceccda.services.ReferenceCCDAValidationService.runValidators(ReferenceCCDAValidationService.java:113)	at org.sitenv.referenceccda.services.ReferenceCCDAValidationService.validateCCDAImplementation(ReferenceCCDAValidationService.java:68) at org.sitenv.referenceccda.services.ReferenceCCDAValidationService.validateCCDA(ReferenceCCDAValidationService.java:54)


```
I can avoid it currently by making above method as `synchronized`.
**Is that going to be fixed soon OR API does not support Multi threading at all.**

**Comment by drbgfc** [comment]
MDHT, the underlying validation library, does not fully support multi-threading due to its underlying EMF dependencies. EMF is not fully thread safe.

**Comment by usmanq8** [comment]
Any plan to have it multi threaded?

**Comment by drbgfc** [comment]
There is no plan that I know of. However, last year some work was done in that direction but I'm pretty sure there was some hard limitations in EMF that kept it from being 100% thread safe. I will try to dig up some more info on this.

**Comment by swmuir** [comment]
The MDHT validation operations  can be leveraged in multithreaded environment.  
If you are using the latest
The piece the supports it is this
`	protected static final ThreadLocal<OCL> EOCL_ENV = new ThreadLocal<OCL>() {
		@Override
		public OCL initialValue() {
			return OCL.newInstance();
		}
	};
`
Can you post of share the processValidateCCDAException code as that is where the exception is being thrown ?
